// AUTO-GENERATED by `npm run import-portfolio` — do not edit by hand.
// Source folder:  D:\\Сайт металлообработка\\Фото_для_портфолио
// Generated at:   2026-05-29T17:12:30.070Z

export interface PortfolioSpec { [key: string]: string }

export interface PortfolioWork {
  id: number;
  slug: string;
  title: string;
  category: string;
  categorySlug: string;
  coverImage: string;
  images: string[];
  description?: string;
  specs?: PortfolioSpec;
}

export interface PortfolioCategory {
  name: string;
  slug: string;
  count: number;
}

export const portfolioWorks: PortfolioWork[] = [
  {
    "id": 2273731703,
    "slug": "askoniya",
    "title": "Аскония",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/askoniya/portfolio-019.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/askoniya/portfolio-019.webp",
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/askoniya/portfolio-020.webp"
    ]
  },
  {
    "id": 2630429615,
    "slug": "serzhinetti",
    "title": "Сержинетти",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/serzhinetti/portfolio-013.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/serzhinetti/portfolio-013.webp",
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/serzhinetti/portfolio-014.webp",
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/serzhinetti/portfolio-015.webp"
    ]
  },
  {
    "id": 18854508,
    "slug": "portfolio-012",
    "title": "Portfolio 012",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-012/portfolio-012.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-012/portfolio-012.webp"
    ]
  },
  {
    "id": 4263488947,
    "slug": "portfolio-017",
    "title": "Portfolio 017",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-017/portfolio-017.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-017/portfolio-017.webp"
    ]
  },
  {
    "id": 186630698,
    "slug": "portfolio-018",
    "title": "Portfolio 018",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-018/portfolio-018.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-018/portfolio-018.webp"
    ]
  },
  {
    "id": 4229786614,
    "slug": "portfolio-021",
    "title": "Portfolio 021",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-021/portfolio-021.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-021/portfolio-021.webp"
    ]
  },
  {
    "id": 4213008995,
    "slug": "portfolio-022",
    "title": "Portfolio 022",
    "category": "Баннер и пленка на время ремонта",
    "categorySlug": "banner-i-plenka-na-vremya-remonta",
    "coverImage": "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-022/portfolio-022.webp",
    "images": [
      "/images/portfolio/banner-i-plenka-na-vremya-remonta/portfolio-022/portfolio-022.webp"
    ]
  },
  {
    "id": 101746679,
    "slug": "vitrazh-dekor",
    "title": "Витраж декор",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/vitrazh-dekor/2023-08-31-decorations-005.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/vitrazh-dekor/2023-08-31-decorations-005.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/vitrazh-dekor/2023-08-31-decorations-006.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/vitrazh-dekor/portfolio-184.webp"
    ]
  },
  {
    "id": 2093946184,
    "slug": "dekorativnyy-podves",
    "title": "Декоративный подвес",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekorativnyy-podves/5246844474317543752.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekorativnyy-podves/5246844474317543752.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekorativnyy-podves/portfolio-212.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekorativnyy-podves/portfolio-213.webp"
    ]
  },
  {
    "id": 3907229614,
    "slug": "dekrativnye-panno",
    "title": "Декративные панно",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekrativnye-panno/portfolio-214.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekrativnye-panno/portfolio-214.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/dekrativnye-panno/portfolio-215.webp"
    ]
  },
  {
    "id": 2190131655,
    "slug": "lobnoe-mesto",
    "title": "Лобное место",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/lobnoe-mesto/portfolio-164.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/lobnoe-mesto/portfolio-164.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/lobnoe-mesto/portfolio-165.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/lobnoe-mesto/portfolio-166.webp"
    ]
  },
  {
    "id": 700029639,
    "slug": "otel",
    "title": "Отель",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/otel/portfolio-169.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/otel/portfolio-169.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/otel/portfolio-183.webp"
    ]
  },
  {
    "id": 2454263529,
    "slug": "park",
    "title": "Парк",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/park/portfolio-144.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/park/portfolio-144.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/park/portfolio-145.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/park/portfolio-146.webp"
    ]
  },
  {
    "id": 1722509054,
    "slug": "samolet",
    "title": "Самолет",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/samolet/portfolio-167.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/samolet/portfolio-167.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/samolet/portfolio-168.webp",
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/samolet/portfolio-216.webp"
    ]
  },
  {
    "id": 3350366150,
    "slug": "portfolio-101",
    "title": "Portfolio 101",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/portfolio-101/portfolio-101.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/portfolio-101/portfolio-101.webp"
    ]
  },
  {
    "id": 3452017602,
    "slug": "portfolio-163",
    "title": "Portfolio 163",
    "category": "Декорации для мероприятий",
    "categorySlug": "dekoratsii-dlya-meropriyatiy",
    "coverImage": "/images/portfolio/dekoratsii-dlya-meropriyatiy/portfolio-163/portfolio-163.webp",
    "images": [
      "/images/portfolio/dekoratsii-dlya-meropriyatiy/portfolio-163/portfolio-163.webp"
    ]
  },
  {
    "id": 1313741464,
    "slug": "portfolio-075",
    "title": "Portfolio 075",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-075/portfolio-075.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-075/portfolio-075.webp"
    ]
  },
  {
    "id": 1364074321,
    "slug": "portfolio-076",
    "title": "Portfolio 076",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-076/portfolio-076.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-076/portfolio-076.webp"
    ]
  },
  {
    "id": 1347296702,
    "slug": "portfolio-077",
    "title": "Portfolio 077",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-077/portfolio-077.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-077/portfolio-077.webp"
    ]
  },
  {
    "id": 1263408607,
    "slug": "portfolio-078",
    "title": "Portfolio 078",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-078/portfolio-078.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-078/portfolio-078.webp"
    ]
  },
  {
    "id": 1246630988,
    "slug": "portfolio-079",
    "title": "Portfolio 079",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-079/portfolio-079.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-079/portfolio-079.webp"
    ]
  },
  {
    "id": 958998704,
    "slug": "portfolio-080",
    "title": "Portfolio 080",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-080/portfolio-080.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-080/portfolio-080.webp"
    ]
  },
  {
    "id": 975776323,
    "slug": "portfolio-081",
    "title": "Portfolio 081",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-081/portfolio-081.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-081/portfolio-081.webp"
    ]
  },
  {
    "id": 992553942,
    "slug": "portfolio-082",
    "title": "Portfolio 082",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-082/portfolio-082.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-082/portfolio-082.webp"
    ]
  },
  {
    "id": 1009331561,
    "slug": "portfolio-083",
    "title": "Portfolio 083",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-083/portfolio-083.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-083/portfolio-083.webp"
    ]
  },
  {
    "id": 1026109180,
    "slug": "portfolio-084",
    "title": "Portfolio 084",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-084/portfolio-084.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-084/portfolio-084.webp"
    ]
  },
  {
    "id": 1042886799,
    "slug": "portfolio-085",
    "title": "Portfolio 085",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-085/portfolio-085.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-085/portfolio-085.webp"
    ]
  },
  {
    "id": 1059664418,
    "slug": "portfolio-086",
    "title": "Portfolio 086",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-086/portfolio-086.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-086/portfolio-086.webp"
    ]
  },
  {
    "id": 1076442037,
    "slug": "portfolio-087",
    "title": "Portfolio 087",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-087/portfolio-087.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-087/portfolio-087.webp"
    ]
  },
  {
    "id": 1093219656,
    "slug": "portfolio-088",
    "title": "Portfolio 088",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-088/portfolio-088.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-088/portfolio-088.webp"
    ]
  },
  {
    "id": 1109997275,
    "slug": "portfolio-089",
    "title": "Portfolio 089",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-089/portfolio-089.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-089/portfolio-089.webp"
    ]
  },
  {
    "id": 1059811513,
    "slug": "portfolio-090",
    "title": "Portfolio 090",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-090/portfolio-090.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-090/portfolio-090.webp"
    ]
  },
  {
    "id": 1043033894,
    "slug": "portfolio-091",
    "title": "Portfolio 091",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-091/portfolio-091.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-091/portfolio-091.webp"
    ]
  },
  {
    "id": 1026256275,
    "slug": "portfolio-092",
    "title": "Portfolio 092",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-092/portfolio-092.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-092/portfolio-092.webp"
    ]
  },
  {
    "id": 1009478656,
    "slug": "portfolio-093",
    "title": "Portfolio 093",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-093/portfolio-093.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-093/portfolio-093.webp"
    ]
  },
  {
    "id": 1126921989,
    "slug": "portfolio-094",
    "title": "Portfolio 094",
    "category": "Интерьерные вывески",
    "categorySlug": "interernye-vyveski",
    "coverImage": "/images/portfolio/interernye-vyveski/portfolio-094/portfolio-094.webp",
    "images": [
      "/images/portfolio/interernye-vyveski/portfolio-094/portfolio-094.webp"
    ]
  },
  {
    "id": 2536170124,
    "slug": "portfolio-126",
    "title": "Portfolio 126",
    "category": "Лук стойки",
    "categorySlug": "luk-stoyki",
    "coverImage": "/images/portfolio/luk-stoyki/portfolio-126/portfolio-126.webp",
    "images": [
      "/images/portfolio/luk-stoyki/portfolio-126/portfolio-126.webp"
    ]
  },
  {
    "id": 2552947743,
    "slug": "portfolio-127",
    "title": "Portfolio 127",
    "category": "Лук стойки",
    "categorySlug": "luk-stoyki",
    "coverImage": "/images/portfolio/luk-stoyki/portfolio-127/portfolio-127.webp",
    "images": [
      "/images/portfolio/luk-stoyki/portfolio-127/portfolio-127.webp"
    ]
  },
  {
    "id": 2636835838,
    "slug": "portfolio-128",
    "title": "Portfolio 128",
    "category": "Лук стойки",
    "categorySlug": "luk-stoyki",
    "coverImage": "/images/portfolio/luk-stoyki/portfolio-128/portfolio-128.webp",
    "images": [
      "/images/portfolio/luk-stoyki/portfolio-128/portfolio-128.webp"
    ]
  },
  {
    "id": 2315952386,
    "slug": "portfolio-002",
    "title": "Portfolio 002",
    "category": "Наклеки на витрины",
    "categorySlug": "nakleki-na-vitriny",
    "coverImage": "/images/portfolio/nakleki-na-vitriny/portfolio-002/portfolio-002.webp",
    "images": [
      "/images/portfolio/nakleki-na-vitriny/portfolio-002/portfolio-002.webp"
    ]
  },
  {
    "id": 2332730005,
    "slug": "portfolio-003",
    "title": "Portfolio 003",
    "category": "Наклеки на витрины",
    "categorySlug": "nakleki-na-vitriny",
    "coverImage": "/images/portfolio/nakleki-na-vitriny/portfolio-003/portfolio-003.webp",
    "images": [
      "/images/portfolio/nakleki-na-vitriny/portfolio-003/portfolio-003.webp"
    ]
  },
  {
    "id": 2215286672,
    "slug": "portfolio-004",
    "title": "Portfolio 004",
    "category": "Наклеки на витрины",
    "categorySlug": "nakleki-na-vitriny",
    "coverImage": "/images/portfolio/nakleki-na-vitriny/portfolio-004/portfolio-004.webp",
    "images": [
      "/images/portfolio/nakleki-na-vitriny/portfolio-004/portfolio-004.webp"
    ]
  },
  {
    "id": 2232064291,
    "slug": "portfolio-005",
    "title": "Portfolio 005",
    "category": "Наклеки на витрины",
    "categorySlug": "nakleki-na-vitriny",
    "coverImage": "/images/portfolio/nakleki-na-vitriny/portfolio-005/portfolio-005.webp",
    "images": [
      "/images/portfolio/nakleki-na-vitriny/portfolio-005/portfolio-005.webp"
    ]
  },
  {
    "id": 2248841910,
    "slug": "portfolio-006",
    "title": "Portfolio 006",
    "category": "Наклеки на витрины",
    "categorySlug": "nakleki-na-vitriny",
    "coverImage": "/images/portfolio/nakleki-na-vitriny/portfolio-006/portfolio-006.webp",
    "images": [
      "/images/portfolio/nakleki-na-vitriny/portfolio-006/portfolio-006.webp"
    ]
  },
  {
    "id": 2265619529,
    "slug": "portfolio-007",
    "title": "Portfolio 007",
    "category": "Наклеки на витрины",
    "categorySlug": "nakleki-na-vitriny",
    "coverImage": "/images/portfolio/nakleki-na-vitriny/portfolio-007/portfolio-007.webp",
    "images": [
      "/images/portfolio/nakleki-na-vitriny/portfolio-007/portfolio-007.webp"
    ]
  },
  {
    "id": 4112773925,
    "slug": "portfolio-177",
    "title": "Portfolio 177",
    "category": "Неоновые вывески",
    "categorySlug": "neonovye-vyveski",
    "coverImage": "/images/portfolio/neonovye-vyveski/portfolio-177/portfolio-177.webp",
    "images": [
      "/images/portfolio/neonovye-vyveski/portfolio-177/portfolio-177.webp"
    ]
  },
  {
    "id": 4146329163,
    "slug": "portfolio-179",
    "title": "Portfolio 179",
    "category": "Неоновые вывески",
    "categorySlug": "neonovye-vyveski",
    "coverImage": "/images/portfolio/neonovye-vyveski/portfolio-179/portfolio-179.webp",
    "images": [
      "/images/portfolio/neonovye-vyveski/portfolio-179/portfolio-179.webp"
    ]
  },
  {
    "id": 138994151,
    "slug": "portfolio-180",
    "title": "Portfolio 180",
    "category": "Неоновые вывески",
    "categorySlug": "neonovye-vyveski",
    "coverImage": "/images/portfolio/neonovye-vyveski/portfolio-180/portfolio-180.webp",
    "images": [
      "/images/portfolio/neonovye-vyveski/portfolio-180/portfolio-180.webp"
    ]
  },
  {
    "id": 122216532,
    "slug": "portfolio-181",
    "title": "Portfolio 181",
    "category": "Неоновые вывески",
    "categorySlug": "neonovye-vyveski",
    "coverImage": "/images/portfolio/neonovye-vyveski/portfolio-181/portfolio-181.webp",
    "images": [
      "/images/portfolio/neonovye-vyveski/portfolio-181/portfolio-181.webp"
    ]
  },
  {
    "id": 172549389,
    "slug": "portfolio-182",
    "title": "Portfolio 182",
    "category": "Неоновые вывески",
    "categorySlug": "neonovye-vyveski",
    "coverImage": "/images/portfolio/neonovye-vyveski/portfolio-182/portfolio-182.webp",
    "images": [
      "/images/portfolio/neonovye-vyveski/portfolio-182/portfolio-182.webp"
    ]
  },
  {
    "id": 2747979672,
    "slug": "brend-voll",
    "title": "Бренд волл",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/brend-voll/portfolio-235.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/brend-voll/portfolio-235.webp",
      "/images/portfolio/oformlenie-mest-prodazh/brend-voll/portfolio-238.webp",
      "/images/portfolio/oformlenie-mest-prodazh/brend-voll/portfolio-239.webp",
      "/images/portfolio/oformlenie-mest-prodazh/brend-voll/portfolio-248.webp"
    ]
  },
  {
    "id": 3583003593,
    "slug": "dekorativnye-svetilniki",
    "title": "Декоративные светильники",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/dekorativnye-svetilniki/portfolio-256.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/dekorativnye-svetilniki/portfolio-256.webp",
      "/images/portfolio/oformlenie-mest-prodazh/dekorativnye-svetilniki/portfolio-257.webp",
      "/images/portfolio/oformlenie-mest-prodazh/dekorativnye-svetilniki/portfolio-258.webp",
      "/images/portfolio/oformlenie-mest-prodazh/dekorativnye-svetilniki/portfolio-259.webp"
    ]
  },
  {
    "id": 2933399239,
    "slug": "navigatsiya",
    "title": "Навигация",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-250.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-250.webp",
      "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-251.webp",
      "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-252.webp",
      "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-253.webp",
      "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-254.webp",
      "/images/portfolio/oformlenie-mest-prodazh/navigatsiya/portfolio-255.webp"
    ]
  },
  {
    "id": 2782217147,
    "slug": "portfolio-236",
    "title": "Portfolio 236",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-236/portfolio-236.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-236/portfolio-236.webp"
    ]
  },
  {
    "id": 2765439528,
    "slug": "portfolio-237",
    "title": "Portfolio 237",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-237/portfolio-237.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-237/portfolio-237.webp"
    ]
  },
  {
    "id": 449686821,
    "slug": "portfolio-241",
    "title": "Portfolio 241",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-241/portfolio-241.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-241/portfolio-241.webp"
    ]
  },
  {
    "id": 399353964,
    "slug": "portfolio-242",
    "title": "Portfolio 242",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-242/portfolio-242.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-242/portfolio-242.webp"
    ]
  },
  {
    "id": 416131583,
    "slug": "portfolio-243",
    "title": "Portfolio 243",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-243/portfolio-243.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-243/portfolio-243.webp"
    ]
  },
  {
    "id": 365798726,
    "slug": "portfolio-244",
    "title": "Portfolio 244",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-244/portfolio-244.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-244/portfolio-244.webp"
    ]
  },
  {
    "id": 382576345,
    "slug": "portfolio-245",
    "title": "Portfolio 245",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-245/portfolio-245.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-245/portfolio-245.webp"
    ]
  },
  {
    "id": 349021107,
    "slug": "portfolio-247",
    "title": "Portfolio 247",
    "category": "Оформление мест продаж",
    "categorySlug": "oformlenie-mest-prodazh",
    "coverImage": "/images/portfolio/oformlenie-mest-prodazh/portfolio-247/portfolio-247.webp",
    "images": [
      "/images/portfolio/oformlenie-mest-prodazh/portfolio-247/portfolio-247.webp"
    ]
  },
  {
    "id": 3187654289,
    "slug": "portfolio-035",
    "title": "Portfolio 035",
    "category": "Панель кронштейн",
    "categorySlug": "panel-kronshteyn",
    "coverImage": "/images/portfolio/panel-kronshteyn/portfolio-035/portfolio-035.webp",
    "images": [
      "/images/portfolio/panel-kronshteyn/portfolio-035/portfolio-035.webp"
    ]
  },
  {
    "id": 1333377719,
    "slug": "portfolio-187",
    "title": "Portfolio 187",
    "category": "Панель кронштейн",
    "categorySlug": "panel-kronshteyn",
    "coverImage": "/images/portfolio/panel-kronshteyn/portfolio-187/portfolio-187.webp",
    "images": [
      "/images/portfolio/panel-kronshteyn/portfolio-187/portfolio-187.webp"
    ]
  },
  {
    "id": 1148823910,
    "slug": "portfolio-188",
    "title": "Portfolio 188",
    "category": "Панель кронштейн",
    "categorySlug": "panel-kronshteyn",
    "coverImage": "/images/portfolio/panel-kronshteyn/portfolio-188/portfolio-188.webp",
    "images": [
      "/images/portfolio/panel-kronshteyn/portfolio-188/portfolio-188.webp"
    ]
  },
  {
    "id": 1165601529,
    "slug": "portfolio-189",
    "title": "Portfolio 189",
    "category": "Панель кронштейн",
    "categorySlug": "panel-kronshteyn",
    "coverImage": "/images/portfolio/panel-kronshteyn/portfolio-189/portfolio-189.webp",
    "images": [
      "/images/portfolio/panel-kronshteyn/portfolio-189/portfolio-189.webp"
    ]
  },
  {
    "id": 3531392903,
    "slug": "portfolio-190",
    "title": "Portfolio 190",
    "category": "Панель кронштейн",
    "categorySlug": "panel-kronshteyn",
    "coverImage": "/images/portfolio/panel-kronshteyn/portfolio-190/portfolio-190.webp",
    "images": [
      "/images/portfolio/panel-kronshteyn/portfolio-190/portfolio-190.webp"
    ]
  },
  {
    "id": 3514615284,
    "slug": "portfolio-191",
    "title": "Portfolio 191",
    "category": "Панель кронштейн",
    "categorySlug": "panel-kronshteyn",
    "coverImage": "/images/portfolio/panel-kronshteyn/portfolio-191/portfolio-191.webp",
    "images": [
      "/images/portfolio/panel-kronshteyn/portfolio-191/portfolio-191.webp"
    ]
  },
  {
    "id": 3471791206,
    "slug": "dlinnye",
    "title": "Длинные",
    "category": "Полки",
    "categorySlug": "polki",
    "coverImage": "/images/portfolio/polki/dlinnye/portfolio-138.webp",
    "images": [
      "/images/portfolio/polki/dlinnye/portfolio-138.webp",
      "/images/portfolio/polki/dlinnye/portfolio-139.webp",
      "/images/portfolio/polki/dlinnye/portfolio-140.webp",
      "/images/portfolio/polki/dlinnye/portfolio-141.webp"
    ]
  },
  {
    "id": 4076704617,
    "slug": "polki-metallichesike",
    "title": "Полки металличесике",
    "category": "Полки",
    "categorySlug": "polki",
    "coverImage": "/images/portfolio/polki/polki-metallichesike/portfolio-131.webp",
    "images": [
      "/images/portfolio/polki/polki-metallichesike/portfolio-131.webp",
      "/images/portfolio/polki/polki-metallichesike/portfolio-132.webp",
      "/images/portfolio/polki/polki-metallichesike/portfolio-133.webp",
      "/images/portfolio/polki/polki-metallichesike/portfolio-135.webp",
      "/images/portfolio/polki/polki-metallichesike/portfolio-137.webp"
    ]
  },
  {
    "id": 283204230,
    "slug": "portfolio-130",
    "title": "Portfolio 130",
    "category": "Полки",
    "categorySlug": "polki",
    "coverImage": "/images/portfolio/polki/portfolio-130/portfolio-130.webp",
    "images": [
      "/images/portfolio/polki/portfolio-130/portfolio-130.webp"
    ]
  },
  {
    "id": 350314706,
    "slug": "portfolio-134",
    "title": "Portfolio 134",
    "category": "Полки",
    "categorySlug": "polki",
    "coverImage": "/images/portfolio/polki/portfolio-134/portfolio-134.webp",
    "images": [
      "/images/portfolio/polki/portfolio-134/portfolio-134.webp"
    ]
  },
  {
    "id": 316759468,
    "slug": "portfolio-136",
    "title": "Portfolio 136",
    "category": "Полки",
    "categorySlug": "polki",
    "coverImage": "/images/portfolio/polki/portfolio-136/portfolio-136.webp",
    "images": [
      "/images/portfolio/polki/portfolio-136/portfolio-136.webp"
    ]
  },
  {
    "id": 554665334,
    "slug": "portfolio-097",
    "title": "Portfolio 097",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-097/portfolio-097.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-097/portfolio-097.webp"
    ]
  },
  {
    "id": 2443550661,
    "slug": "portfolio-104",
    "title": "Portfolio 104",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-104/portfolio-104.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-104/portfolio-104.webp"
    ]
  },
  {
    "id": 2426773042,
    "slug": "portfolio-105",
    "title": "Portfolio 105",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-105/portfolio-105.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-105/portfolio-105.webp"
    ]
  },
  {
    "id": 2409995423,
    "slug": "portfolio-106",
    "title": "Portfolio 106",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-106/portfolio-106.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-106/portfolio-106.webp"
    ]
  },
  {
    "id": 2493883518,
    "slug": "portfolio-109",
    "title": "Portfolio 109",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-109/portfolio-109.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-109/portfolio-109.webp"
    ]
  },
  {
    "id": 2275627376,
    "slug": "portfolio-110",
    "title": "Portfolio 110",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-110/portfolio-110.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-110/portfolio-110.webp"
    ]
  },
  {
    "id": 2359515471,
    "slug": "portfolio-115",
    "title": "Portfolio 115",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-115/portfolio-115.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-115/portfolio-115.webp"
    ]
  },
  {
    "id": 2393070709,
    "slug": "portfolio-117",
    "title": "Portfolio 117",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-117/portfolio-117.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-117/portfolio-117.webp"
    ]
  },
  {
    "id": 2409848328,
    "slug": "portfolio-118",
    "title": "Portfolio 118",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-118/portfolio-118.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-118/portfolio-118.webp"
    ]
  },
  {
    "id": 413856120,
    "slug": "portfolio-121",
    "title": "Portfolio 121",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-121/portfolio-121.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-121/portfolio-121.webp"
    ]
  },
  {
    "id": 464188977,
    "slug": "portfolio-122",
    "title": "Portfolio 122",
    "category": "Пристенные рейлы",
    "categorySlug": "pristennye-reyly",
    "coverImage": "/images/portfolio/pristennye-reyly/portfolio-122/portfolio-122.webp",
    "images": [
      "/images/portfolio/pristennye-reyly/portfolio-122/portfolio-122.webp"
    ]
  },
  {
    "id": 322360781,
    "slug": "resepshen-1",
    "title": "Ресепшен 1",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/resepshen-1/portfolio-154.webp",
    "images": [
      "/images/portfolio/resepshn/resepshen-1/portfolio-154.webp",
      "/images/portfolio/resepshn/resepshen-1/portfolio-155.webp",
      "/images/portfolio/resepshn/resepshen-1/portfolio-157.webp"
    ]
  },
  {
    "id": 890218673,
    "slug": "resepshn-2",
    "title": "Ресепшн 2",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/resepshn-2/portfolio-142.webp",
    "images": [
      "/images/portfolio/resepshn/resepshn-2/portfolio-142.webp",
      "/images/portfolio/resepshn/resepshn-2/portfolio-143.webp"
    ]
  },
  {
    "id": 873441054,
    "slug": "resepshn-3",
    "title": "Ресепшн 3",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/resepshn-3/portfolio-148.webp",
    "images": [
      "/images/portfolio/resepshn/resepshn-3/portfolio-148.webp",
      "/images/portfolio/resepshn/resepshn-3/portfolio-149.webp",
      "/images/portfolio/resepshn/resepshn-3/portfolio-152.webp"
    ]
  },
  {
    "id": 923773911,
    "slug": "resepshn-4",
    "title": "Ресепшн 4",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/resepshn-4/portfolio-159.webp",
    "images": [
      "/images/portfolio/resepshn/resepshn-4/portfolio-159.webp",
      "/images/portfolio/resepshn/resepshn-4/portfolio-160.webp"
    ]
  },
  {
    "id": 3601961715,
    "slug": "portfolio-147",
    "title": "Portfolio 147",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/portfolio-147/portfolio-147.webp",
    "images": [
      "/images/portfolio/resepshn/portfolio-147/portfolio-147.webp"
    ]
  },
  {
    "id": 3786662619,
    "slug": "portfolio-150",
    "title": "Portfolio 150",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/portfolio-150/portfolio-150.webp",
    "images": [
      "/images/portfolio/resepshn/portfolio-150/portfolio-150.webp"
    ]
  },
  {
    "id": 3769885000,
    "slug": "portfolio-151",
    "title": "Portfolio 151",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/portfolio-151/portfolio-151.webp",
    "images": [
      "/images/portfolio/resepshn/portfolio-151/portfolio-151.webp"
    ]
  },
  {
    "id": 1353466579,
    "slug": "portfolio-161",
    "title": "Portfolio 161",
    "category": "Ресепшн",
    "categorySlug": "resepshn",
    "coverImage": "/images/portfolio/resepshn/portfolio-161/portfolio-161.webp",
    "images": [
      "/images/portfolio/resepshn/portfolio-161/portfolio-161.webp"
    ]
  },
  {
    "id": 341131527,
    "slug": "portfolio-107",
    "title": "Portfolio 107",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-107/portfolio-107.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-107/portfolio-107.webp"
    ]
  },
  {
    "id": 156577718,
    "slug": "portfolio-108",
    "title": "Portfolio 108",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-108/portfolio-108.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-108/portfolio-108.webp"
    ]
  },
  {
    "id": 374833860,
    "slug": "portfolio-111",
    "title": "Portfolio 111",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-111/portfolio-111.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-111/portfolio-111.webp"
    ]
  },
  {
    "id": 425166717,
    "slug": "portfolio-112",
    "title": "Portfolio 112",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-112/portfolio-112.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-112/portfolio-112.webp"
    ]
  },
  {
    "id": 408389098,
    "slug": "portfolio-113",
    "title": "Portfolio 113",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-113/portfolio-113.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-113/portfolio-113.webp"
    ]
  },
  {
    "id": 324501003,
    "slug": "portfolio-114",
    "title": "Portfolio 114",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-114/portfolio-114.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-114/portfolio-114.webp"
    ]
  },
  {
    "id": 358056241,
    "slug": "portfolio-116",
    "title": "Portfolio 116",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-116/portfolio-116.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-116/portfolio-116.webp"
    ]
  },
  {
    "id": 240612908,
    "slug": "portfolio-119",
    "title": "Portfolio 119",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-119/portfolio-119.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-119/portfolio-119.webp"
    ]
  },
  {
    "id": 2236605116,
    "slug": "portfolio-120",
    "title": "Portfolio 120",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-120/portfolio-120.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-120/portfolio-120.webp"
    ]
  },
  {
    "id": 2169494640,
    "slug": "portfolio-124",
    "title": "Portfolio 124",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-124/portfolio-124.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-124/portfolio-124.webp"
    ]
  },
  {
    "id": 2186272259,
    "slug": "portfolio-125",
    "title": "Portfolio 125",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-125/portfolio-125.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-125/portfolio-125.webp"
    ]
  },
  {
    "id": 2387603687,
    "slug": "portfolio-129",
    "title": "Portfolio 129",
    "category": "Рейлы отдельно стоящие",
    "categorySlug": "reyly-otdelno-stoyaschie",
    "coverImage": "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-129/portfolio-129.webp",
    "images": [
      "/images/portfolio/reyly-otdelno-stoyaschie/portfolio-129/portfolio-129.webp"
    ]
  },
  {
    "id": 1447230034,
    "slug": "oromlenie-1",
    "title": "Оромление 1",
    "category": "Сезонное оформление",
    "categorySlug": "sezonnoe-oformlenie",
    "coverImage": "/images/portfolio/sezonnoe-oformlenie/oromlenie-1/portfolio-023.webp",
    "images": [
      "/images/portfolio/sezonnoe-oformlenie/oromlenie-1/portfolio-023.webp",
      "/images/portfolio/sezonnoe-oformlenie/oromlenie-1/portfolio-024.webp"
    ]
  },
  {
    "id": 1103075852,
    "slug": "ofrmlenie-2",
    "title": "Офрмление 2",
    "category": "Сезонное оформление",
    "categorySlug": "sezonnoe-oformlenie",
    "coverImage": "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-027.webp",
    "images": [
      "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-027.webp",
      "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-028.webp",
      "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-029.webp",
      "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-030.webp",
      "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-031.webp",
      "/images/portfolio/sezonnoe-oformlenie/ofrmlenie-2/portfolio-032.webp"
    ]
  },
  {
    "id": 692933307,
    "slug": "portfolio-026",
    "title": "Portfolio 026",
    "category": "Сезонное оформление",
    "categorySlug": "sezonnoe-oformlenie",
    "coverImage": "/images/portfolio/sezonnoe-oformlenie/portfolio-026/portfolio-026.webp",
    "images": [
      "/images/portfolio/sezonnoe-oformlenie/portfolio-026/portfolio-026.webp"
    ]
  },
  {
    "id": 1126611921,
    "slug": "portfolio-095",
    "title": "Portfolio 095",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-095/portfolio-095.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-095/portfolio-095.webp"
    ]
  },
  {
    "id": 1076279064,
    "slug": "portfolio-096",
    "title": "Portfolio 096",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-096/portfolio-096.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-096/portfolio-096.webp"
    ]
  },
  {
    "id": 1042723826,
    "slug": "portfolio-098",
    "title": "Portfolio 098",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-098/portfolio-098.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-098/portfolio-098.webp"
    ]
  },
  {
    "id": 1059501445,
    "slug": "portfolio-099",
    "title": "Portfolio 099",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-099/portfolio-099.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-099/portfolio-099.webp"
    ]
  },
  {
    "id": 3179151744,
    "slug": "portfolio-100",
    "title": "Portfolio 100",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-100/portfolio-100.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-100/portfolio-100.webp"
    ]
  },
  {
    "id": 3212706982,
    "slug": "portfolio-102",
    "title": "Portfolio 102",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-102/portfolio-102.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-102/portfolio-102.webp"
    ]
  },
  {
    "id": 3229484601,
    "slug": "portfolio-103",
    "title": "Portfolio 103",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-103/portfolio-103.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-103/portfolio-103.webp"
    ]
  },
  {
    "id": 1216567679,
    "slug": "portfolio-123",
    "title": "Portfolio 123",
    "category": "Стоки и консоли",
    "categorySlug": "stoki-i-konsoli",
    "coverImage": "/images/portfolio/stoki-i-konsoli/portfolio-123/portfolio-123.webp",
    "images": [
      "/images/portfolio/stoki-i-konsoli/portfolio-123/portfolio-123.webp"
    ]
  },
  {
    "id": 1183218565,
    "slug": "ekran-1",
    "title": "Экран 1",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/ekran-1/portfolio-205.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/ekran-1/portfolio-205.webp",
      "/images/portfolio/svetodiodnye-ekrany/ekran-1/portfolio-206.webp"
    ]
  },
  {
    "id": 2216274357,
    "slug": "portfolio-198",
    "title": "Portfolio 198",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-198/portfolio-198.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-198/portfolio-198.webp"
    ]
  },
  {
    "id": 2199496738,
    "slug": "portfolio-199",
    "title": "Portfolio 199",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-199/portfolio-199.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-199/portfolio-199.webp"
    ]
  },
  {
    "id": 1373579130,
    "slug": "portfolio-201",
    "title": "Portfolio 201",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-201/portfolio-201.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-201/portfolio-201.webp"
    ]
  },
  {
    "id": 1356801511,
    "slug": "portfolio-202",
    "title": "Portfolio 202",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-202/portfolio-202.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-202/portfolio-202.webp"
    ]
  },
  {
    "id": 1340023892,
    "slug": "portfolio-203",
    "title": "Portfolio 203",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-203/portfolio-203.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-203/portfolio-203.webp"
    ]
  },
  {
    "id": 1323246273,
    "slug": "portfolio-204",
    "title": "Portfolio 204",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-204/portfolio-204.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-204/portfolio-204.webp"
    ]
  },
  {
    "id": 1272913416,
    "slug": "portfolio-207",
    "title": "Portfolio 207",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-207/portfolio-207.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-207/portfolio-207.webp"
    ]
  },
  {
    "id": 1256135797,
    "slug": "portfolio-208",
    "title": "Portfolio 208",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-208/portfolio-208.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-208/portfolio-208.webp"
    ]
  },
  {
    "id": 1239358178,
    "slug": "portfolio-209",
    "title": "Portfolio 209",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-209/portfolio-209.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-209/portfolio-209.webp"
    ]
  },
  {
    "id": 1306321559,
    "slug": "portfolio-211",
    "title": "Portfolio 211",
    "category": "Светодиодные экраны",
    "categorySlug": "svetodiodnye-ekrany",
    "coverImage": "/images/portfolio/svetodiodnye-ekrany/portfolio-211/portfolio-211.webp",
    "images": [
      "/images/portfolio/svetodiodnye-ekrany/portfolio-211/portfolio-211.webp"
    ]
  },
  {
    "id": 433812337,
    "slug": "svetovoy-korob-1",
    "title": "Световой короб 1",
    "category": "Световые короба",
    "categorySlug": "svetovye-koroba",
    "coverImage": "/images/portfolio/svetovye-koroba/svetovoy-korob-1/portfolio-194.webp",
    "images": [
      "/images/portfolio/svetovye-koroba/svetovoy-korob-1/portfolio-194.webp",
      "/images/portfolio/svetovye-koroba/svetovoy-korob-1/portfolio-195.webp",
      "/images/portfolio/svetovye-koroba/svetovoy-korob-1/portfolio-196.webp",
      "/images/portfolio/svetovye-koroba/svetovoy-korob-1/portfolio-197.webp"
    ]
  },
  {
    "id": 383479480,
    "slug": "svetovoy-korob-2",
    "title": "Световой короб 2",
    "category": "Световые короба",
    "categorySlug": "svetovye-koroba",
    "coverImage": "/images/portfolio/svetovye-koroba/svetovoy-korob-2/portfolio-192.webp",
    "images": [
      "/images/portfolio/svetovye-koroba/svetovoy-korob-2/portfolio-192.webp",
      "/images/portfolio/svetovye-koroba/svetovoy-korob-2/portfolio-193.webp"
    ]
  },
  {
    "id": 3862033864,
    "slug": "portfolio-217",
    "title": "Portfolio 217",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-217/portfolio-217.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-217/portfolio-217.webp"
    ]
  },
  {
    "id": 3845256245,
    "slug": "portfolio-218",
    "title": "Portfolio 218",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-218/portfolio-218.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-218/portfolio-218.webp"
    ]
  },
  {
    "id": 3828478626,
    "slug": "portfolio-219",
    "title": "Portfolio 219",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-219/portfolio-219.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-219/portfolio-219.webp"
    ]
  },
  {
    "id": 1412751753,
    "slug": "portfolio-221",
    "title": "Portfolio 221",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-221/portfolio-221.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-221/portfolio-221.webp"
    ]
  },
  {
    "id": 1362418896,
    "slug": "portfolio-222",
    "title": "Portfolio 222",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-222/portfolio-222.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-222/portfolio-222.webp"
    ]
  },
  {
    "id": 1379196515,
    "slug": "portfolio-223",
    "title": "Portfolio 223",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-223/portfolio-223.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-223/portfolio-223.webp"
    ]
  },
  {
    "id": 1463084610,
    "slug": "portfolio-224",
    "title": "Portfolio 224",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-224/portfolio-224.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-224/portfolio-224.webp"
    ]
  },
  {
    "id": 1479862229,
    "slug": "portfolio-225",
    "title": "Portfolio 225",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-225/portfolio-225.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-225/portfolio-225.webp"
    ]
  },
  {
    "id": 1429529372,
    "slug": "portfolio-226",
    "title": "Portfolio 226",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-226/portfolio-226.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-226/portfolio-226.webp"
    ]
  },
  {
    "id": 1446306991,
    "slug": "portfolio-227",
    "title": "Portfolio 227",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-227/portfolio-227.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-227/portfolio-227.webp"
    ]
  },
  {
    "id": 1530195086,
    "slug": "portfolio-228",
    "title": "Portfolio 228",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-228/portfolio-228.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-228/portfolio-228.webp"
    ]
  },
  {
    "id": 1546972705,
    "slug": "portfolio-229",
    "title": "Portfolio 229",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-229/portfolio-229.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-229/portfolio-229.webp"
    ]
  },
  {
    "id": 1496786943,
    "slug": "portfolio-230",
    "title": "Portfolio 230",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-230/portfolio-230.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-230/portfolio-230.webp"
    ]
  },
  {
    "id": 1480009324,
    "slug": "portfolio-231",
    "title": "Portfolio 231",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-231/portfolio-231.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-231/portfolio-231.webp"
    ]
  },
  {
    "id": 1530342181,
    "slug": "portfolio-232",
    "title": "Portfolio 232",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-232/portfolio-232.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-232/portfolio-232.webp"
    ]
  },
  {
    "id": 1513564562,
    "slug": "portfolio-233",
    "title": "Portfolio 233",
    "category": "Текстильные лайтбоксы",
    "categorySlug": "tekstilnye-laytboksy",
    "coverImage": "/images/portfolio/tekstilnye-laytboksy/portfolio-233/portfolio-233.webp",
    "images": [
      "/images/portfolio/tekstilnye-laytboksy/portfolio-233/portfolio-233.webp"
    ]
  },
  {
    "id": 3194884251,
    "slug": "portfolio-170",
    "title": "Portfolio 170",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-170/portfolio-170.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-170/portfolio-170.webp"
    ]
  },
  {
    "id": 3178106632,
    "slug": "portfolio-171",
    "title": "Portfolio 171",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-171/portfolio-171.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-171/portfolio-171.webp"
    ]
  },
  {
    "id": 3228439489,
    "slug": "portfolio-172",
    "title": "Portfolio 172",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-172/portfolio-172.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-172/portfolio-172.webp"
    ]
  },
  {
    "id": 3211661870,
    "slug": "portfolio-173",
    "title": "Portfolio 173",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-173/portfolio-173.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-173/portfolio-173.webp"
    ]
  },
  {
    "id": 3261994727,
    "slug": "portfolio-174",
    "title": "Portfolio 174",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-174/portfolio-174.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-174/portfolio-174.webp"
    ]
  },
  {
    "id": 3245217108,
    "slug": "portfolio-175",
    "title": "Portfolio 175",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-175/portfolio-175.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-175/portfolio-175.webp"
    ]
  },
  {
    "id": 3295549965,
    "slug": "portfolio-176",
    "title": "Portfolio 176",
    "category": "Уникальное торговое оборудование",
    "categorySlug": "unikalnoe-torgovoe-oborudovanie",
    "coverImage": "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-176/portfolio-176.webp",
    "images": [
      "/images/portfolio/unikalnoe-torgovoe-oborudovanie/portfolio-176/portfolio-176.webp"
    ]
  },
  {
    "id": 1862635582,
    "slug": "grandramadzh",
    "title": "Грандрамадж",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/grandramadzh/portfolio-066.webp",
    "images": [
      "/images/portfolio/vyveski/grandramadzh/portfolio-066.webp",
      "/images/portfolio/vyveski/grandramadzh/portfolio-067.webp"
    ]
  },
  {
    "id": 3109284485,
    "slug": "oksouno",
    "title": "Оксоуно",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/oksouno/portfolio-070.webp",
    "images": [
      "/images/portfolio/vyveski/oksouno/portfolio-070.webp",
      "/images/portfolio/vyveski/oksouno/portfolio-071.webp"
    ]
  },
  {
    "id": 3355369857,
    "slug": "emka",
    "title": "Эмка",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/emka/portfolio-056.webp",
    "images": [
      "/images/portfolio/vyveski/emka/portfolio-056.webp",
      "/images/portfolio/vyveski/emka/portfolio-057.webp"
    ]
  },
  {
    "id": 2144226330,
    "slug": "portfolio-033",
    "title": "Portfolio 033",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-033/portfolio-033.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-033/portfolio-033.webp"
    ]
  },
  {
    "id": 2060338235,
    "slug": "portfolio-034",
    "title": "Portfolio 034",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-034/portfolio-034.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-034/portfolio-034.webp"
    ]
  },
  {
    "id": 2093893473,
    "slug": "portfolio-036",
    "title": "Portfolio 036",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-036/portfolio-036.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-036/portfolio-036.webp"
    ]
  },
  {
    "id": 2077115854,
    "slug": "portfolio-037",
    "title": "Portfolio 037",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-037/portfolio-037.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-037/portfolio-037.webp"
    ]
  },
  {
    "id": 1993227759,
    "slug": "portfolio-038",
    "title": "Portfolio 038",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-038/portfolio-038.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-038/portfolio-038.webp"
    ]
  },
  {
    "id": 1976450140,
    "slug": "portfolio-039",
    "title": "Portfolio 039",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-039/portfolio-039.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-039/portfolio-039.webp"
    ]
  },
  {
    "id": 1958539688,
    "slug": "portfolio-040",
    "title": "Portfolio 040",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-040/portfolio-040.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-040/portfolio-040.webp"
    ]
  },
  {
    "id": 1975317307,
    "slug": "portfolio-041",
    "title": "Portfolio 041",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-041/portfolio-041.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-041/portfolio-041.webp"
    ]
  },
  {
    "id": 1992094926,
    "slug": "portfolio-042",
    "title": "Portfolio 042",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-042/portfolio-042.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-042/portfolio-042.webp"
    ]
  },
  {
    "id": 2008872545,
    "slug": "portfolio-043",
    "title": "Portfolio 043",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-043/portfolio-043.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-043/portfolio-043.webp"
    ]
  },
  {
    "id": 2025650164,
    "slug": "portfolio-044",
    "title": "Portfolio 044",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-044/portfolio-044.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-044/portfolio-044.webp"
    ]
  },
  {
    "id": 2042427783,
    "slug": "portfolio-045",
    "title": "Portfolio 045",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-045/portfolio-045.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-045/portfolio-045.webp"
    ]
  },
  {
    "id": 2059205402,
    "slug": "portfolio-046",
    "title": "Portfolio 046",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-046/portfolio-046.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-046/portfolio-046.webp"
    ]
  },
  {
    "id": 2075983021,
    "slug": "portfolio-047",
    "title": "Portfolio 047",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-047/portfolio-047.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-047/portfolio-047.webp"
    ]
  },
  {
    "id": 1824318736,
    "slug": "portfolio-048",
    "title": "Portfolio 048",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-048/portfolio-048.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-048/portfolio-048.webp"
    ]
  },
  {
    "id": 1841096355,
    "slug": "portfolio-049",
    "title": "Portfolio 049",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-049/portfolio-049.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-049/portfolio-049.webp"
    ]
  },
  {
    "id": 2059352497,
    "slug": "portfolio-050",
    "title": "Portfolio 050",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-050/portfolio-050.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-050/portfolio-050.webp"
    ]
  },
  {
    "id": 2042574878,
    "slug": "portfolio-051",
    "title": "Portfolio 051",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-051/portfolio-051.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-051/portfolio-051.webp"
    ]
  },
  {
    "id": 2025797259,
    "slug": "portfolio-052",
    "title": "Portfolio 052",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-052/portfolio-052.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-052/portfolio-052.webp"
    ]
  },
  {
    "id": 2009019640,
    "slug": "portfolio-053",
    "title": "Portfolio 053",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-053/portfolio-053.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-053/portfolio-053.webp"
    ]
  },
  {
    "id": 2126462973,
    "slug": "portfolio-054",
    "title": "Portfolio 054",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-054/portfolio-054.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-054/portfolio-054.webp"
    ]
  },
  {
    "id": 2109685354,
    "slug": "portfolio-055",
    "title": "Portfolio 055",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-055/portfolio-055.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-055/portfolio-055.webp"
    ]
  },
  {
    "id": 1925131545,
    "slug": "portfolio-058",
    "title": "Portfolio 058",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-058/portfolio-058.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-058/portfolio-058.webp"
    ]
  },
  {
    "id": 2160165306,
    "slug": "portfolio-060",
    "title": "Portfolio 060",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-060/portfolio-060.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-060/portfolio-060.webp"
    ]
  },
  {
    "id": 2176942925,
    "slug": "portfolio-061",
    "title": "Portfolio 061",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-061/portfolio-061.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-061/portfolio-061.webp"
    ]
  },
  {
    "id": 2126610068,
    "slug": "portfolio-062",
    "title": "Portfolio 062",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-062/portfolio-062.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-062/portfolio-062.webp"
    ]
  },
  {
    "id": 2143387687,
    "slug": "portfolio-063",
    "title": "Portfolio 063",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-063/portfolio-063.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-063/portfolio-063.webp"
    ]
  },
  {
    "id": 2093054830,
    "slug": "portfolio-064",
    "title": "Portfolio 064",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-064/portfolio-064.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-064/portfolio-064.webp"
    ]
  },
  {
    "id": 2109832449,
    "slug": "portfolio-065",
    "title": "Portfolio 065",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-065/portfolio-065.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-065/portfolio-065.webp"
    ]
  },
  {
    "id": 2025944354,
    "slug": "portfolio-068",
    "title": "Portfolio 068",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-068/portfolio-068.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-068/portfolio-068.webp"
    ]
  },
  {
    "id": 2042721973,
    "slug": "portfolio-069",
    "title": "Portfolio 069",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-069/portfolio-069.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-069/portfolio-069.webp"
    ]
  },
  {
    "id": 3905184777,
    "slug": "portfolio-072",
    "title": "Portfolio 072",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-072/portfolio-072.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-072/portfolio-072.webp"
    ]
  },
  {
    "id": 3888407158,
    "slug": "portfolio-073",
    "title": "Portfolio 073",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-073/portfolio-073.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-073/portfolio-073.webp"
    ]
  },
  {
    "id": 3938740015,
    "slug": "portfolio-074",
    "title": "Portfolio 074",
    "category": "Вывески",
    "categorySlug": "vyveski",
    "coverImage": "/images/portfolio/vyveski/portfolio-074/portfolio-074.webp",
    "images": [
      "/images/portfolio/vyveski/portfolio-074/portfolio-074.webp"
    ]
  }
];

export const portfolioCategories: PortfolioCategory[] = [
  {
    "name": "Баннер и пленка на время ремонта",
    "slug": "banner-i-plenka-na-vremya-remonta",
    "count": 7
  },
  {
    "name": "Вывески",
    "slug": "vyveski",
    "count": 37
  },
  {
    "name": "Декорации для мероприятий",
    "slug": "dekoratsii-dlya-meropriyatiy",
    "count": 9
  },
  {
    "name": "Интерьерные вывески",
    "slug": "interernye-vyveski",
    "count": 20
  },
  {
    "name": "Лук стойки",
    "slug": "luk-stoyki",
    "count": 3
  },
  {
    "name": "Наклеки на витрины",
    "slug": "nakleki-na-vitriny",
    "count": 6
  },
  {
    "name": "Неоновые вывески",
    "slug": "neonovye-vyveski",
    "count": 5
  },
  {
    "name": "Оформление мест продаж",
    "slug": "oformlenie-mest-prodazh",
    "count": 11
  },
  {
    "name": "Панель кронштейн",
    "slug": "panel-kronshteyn",
    "count": 6
  },
  {
    "name": "Полки",
    "slug": "polki",
    "count": 5
  },
  {
    "name": "Пристенные рейлы",
    "slug": "pristennye-reyly",
    "count": 11
  },
  {
    "name": "Рейлы отдельно стоящие",
    "slug": "reyly-otdelno-stoyaschie",
    "count": 12
  },
  {
    "name": "Ресепшн",
    "slug": "resepshn",
    "count": 8
  },
  {
    "name": "Световые короба",
    "slug": "svetovye-koroba",
    "count": 2
  },
  {
    "name": "Светодиодные экраны",
    "slug": "svetodiodnye-ekrany",
    "count": 11
  },
  {
    "name": "Сезонное оформление",
    "slug": "sezonnoe-oformlenie",
    "count": 3
  },
  {
    "name": "Стоки и консоли",
    "slug": "stoki-i-konsoli",
    "count": 8
  },
  {
    "name": "Текстильные лайтбоксы",
    "slug": "tekstilnye-laytboksy",
    "count": 16
  },
  {
    "name": "Уникальное торговое оборудование",
    "slug": "unikalnoe-torgovoe-oborudovanie",
    "count": 7
  }
];
